### ISSUE TITLE
Typo in xz codec feature 

### ISSUE THREAD

**Issue by jfuechsl** [creativcoder/avrow#9]
Hi,
this looks like a typo and the feature string in that line should be "xz", right?
https://github.com/creativcoder/avrow/blob/c60f3760c28decb5e491b9b4ddadcfb3553d5ff2/src/codec.rs#L268-L269

**Comment by creativcoder** [comment]
Hey @jfuechsl good catch! Wanna file a fix for that?

**Comment by jfuechsl** [comment]
Hi @creativcoder, I will.
